### ISSUE TITLE
Wanted to share icons with you

### ISSUE THREAD

**Issue by egeant94** [nouser2013/lighthouse-v2-manager#3]
Hello, I made 2 little fancy icons for both ON and OFF shortucts, I thank you for creating this software and wanted some cool icon for my windows start menu : 
![image](https://user-images.githubusercontent.com/56257277/91046810-5f8f0200-e619-11ea-966f-e400978b86dd.png)
Just wanted to share it with you somehow, sorry for creating an issue
[base_station_icons.zip](https://github.com/nouser2013/lighthouse-v2-manager/files/5117873/base_station_icons.zip)

**Comment by nouser2013** [comment]
Hi egeant94, thanks fro sharing, I like them.

* Would you be willing to share the source files as well? Ideally in SVG format?
* Also, I've created a new branch, but it would be under my name. I'd update the `readme.md` to reflect credits. Is that ok?

Cheers

**Comment by egeant94** [comment]
Yes that's perfectly fine thank you
Unfortunately I can't have the SVG format for the icons, because I took a base station 2.0 png on google image and add the 3d text / circle on it with photoshop cs6.
Here's a .zip with the raw png, the .png results and the png converted in .ico
[Icons.zip](https://github.com/nouser2013/lighthouse-v2-manager/files/5118778/Icons.zip)
The ico are in 256*256 and seems to adapt well whatever the size tho
![image](https://user-images.githubusercontent.com/56257277/91064383-75a7bd00-e62f-11ea-9469-a40f81baede4.png)
![image](https://user-images.githubusercontent.com/56257277/91064475-96701280-e62f-11ea-8fb4-b1ed6adafbe2.png)
Thanks for according me your time 💯 
(the base png is taken directly from [Vive's website](https://www.vive.com/eu/accessory/base-station2/) so I don't know if it's copyright safe)

**Comment by nouser2013** [comment]
Hi, alright, well, then I guess the sources aren't that important. I just merged the branch, updated the readme and created a new release... Thanks again :)

**Comment by egeant94** [comment]
Thank you for the credits, that's too much honor ! You did much more than me overall 😄 
Your application is saving me a ton of times quitting / relaunching steam VR to control my base stations (thx windows 2004)
Thank you for that great app 🙏
