### ISSUE TITLE
"> LH switched to 'off' successfully... >> disconnected." but base stations are still on

### ISSUE THREAD

**Issue by skyrockss** [nouser2013/lighthouse-v2-manager#6]
So I've successfully installed your program as I've gotten the mac address multiple times and I have the icons and everything setup in a folder (with no errors) everytime I open the LHv2-OFF app i get the message

"
=== LightHouse V2 Manager ===

>> MODE: switch lighthouses OFF
   * (mac id)
   * (mac id)

>> Trying to connect to BLE MAC '(mac id)'...
>> '(mac id)' connected...
>> LH switched to 'off' successfully...
>> disconnected.

but the base stations are still on when i check them ive checked my bluetooth dongle and it does support low energy Bluetooth since I have the "Le enumerator" in device manager, I also closed all steam vr programs including steam but no luck. Im kind of stuck on what to do here also my bluetooth dongle is this 

https://www.amazon.com/gp/product/B08FHW5452/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 

Also forgot to mention i am using the HTC version of the light houses dont know if that has anything to do with it (2.0 not 1.0)

**Comment by nouser2013** [comment]
Hi, as this is the first time I'm hearing about an installation not working, I tend to assume an incompatible USB dongle. You write that you've tried several times and it does not work.

Could you please try this:
- download GATTBrowser (on Android Phone)
- open it and let it search
- find one of your (running) lighthouses named `LHB-12345678`
- connect to it (blue arrow)
- find the characteristic `00001525-1212-efde-1523-785feabcd124` (should be Read-Write-Notify)
- write a `00` (Hex!) to it. This should turn the LH off.
- write a `01` (Hex!) to it. This should turn the LH back on.

In case these commands work, it's your dongle. In case the LH remains on or GATTBrowser reports an error, it seems that they changed something in the firmware that I don't yet know about.

**Comment by skyrockss** [comment]
> Hi, as this is the first time I'm hearing about an installation not working, I tend to assume an incompatible USB dongle. You write that you've tried several times and it does not work.
> 
> Could you please try this:
> 
> * download GATTBrowser (on Android Phone)
> * open it and let it search
> * find one of your (running) lighthouses named `LHB-12345678`
> * connect to it (blue arrow)
> * find the characteristic `00001525-1212-efde-1523-785feabcd124` (should be Read-Write-Notify)
> * write a `00` (Hex!) to it. This should turn the LH off.
> * write a `01` (Hex!) to it. This should turn the LH back on.
> 
> In case these commands work, it's your dongle. In case the LH remains on or GATTBrowser reports an error, it seems that they changed something in the firmware that I don't yet know about.

Hi i did as you told me to (with iphone because i don’t have android) and the light houses still remains on.

**Comment by nouser2013** [comment]
Ok, then I'd love to get my hands on it as this seems to be a very old or very new firmware version which behaves differently.

Could you open GATTBrowser again and connect to the LH (blue arrow) and find the `Device Information Service`. Probably at the bottom of the screen. There, find the items
* `Manufacturer Name String`
* `Model Number String`
* `Hardware Revision String` and 
* `Firmware Revision String`

Could you post their respective `String` values here (not Hex)?

**Comment by skyrockss** [comment]
sure, here they are 

manufacture name string 56616c766520436f72702e

model number string 31303034

hardware revision string 302e30

firmware revision string 523a2020312e312e363237373234382c204d3a2020302e312e383133383631352c20423a58582e58582e58585858585858

**Comment by skyrockss** [comment]
Sure here they are 

manufacture Valve Corp.

model number 1004

hardware revision 0.0

firmware revision R:  1.1.6277248, M:  0.1.8138615, B:XX.XX.XXXXXXX

**Comment by nouser2013** [comment]
Alright, we're closing in :) My FW String reads (rest is the same):

    R: 2.9.2004771
    M: 1.8.2004742
    B: 3.4.3782793

So, new question: do yours look like these:
![51PqarSBJvL _SL1500_](https://user-images.githubusercontent.com/6624032/101136891-429d9e00-360e-11eb-9966-cfed386994f8.jpg)

If not and yours have a flat front, this software is not made for them - they're the V1 lighthouses and can be controlled via ManniX's software. See link in the readme.md.

If they do look like this (round front), they seem to run a very old firmware. Best to get this updated seems via Headset. If you dont own a Vive Headset, try this: https://www.vive.com/us/support/vive/category_howto/updating-the-base-stations-via-cable-connection.html

**Comment by skyrockss** [comment]
Hi I am using the 2.0 base stations (round front) but in steam vr i dont have an option to update the base stations. (even when plugged in) is there a way to manually update the base stations? 
![image](https://user-images.githubusercontent.com/75432389/101162901-cb551380-35e7-11eb-8913-8ca1be285438.png)

**Comment by nouser2013** [comment]
Hm, you can try:

1. Powercycle the faulty basestation. (This would reset a base station communication failure.)
2. Open SteamVR->Settings->Base Station and click Recover from Incomplete Update.
3. If it fails again, move it closer to your link box.

If that does not work, I'm afraid you should reach out to Steam for help. In any case, do not upload firmware manually, there seems to be consensus that you might be overwriting calibration data.

**Comment by skyrockss** [comment]
the base stations work fine though the only issue is there is no option to update btw im using seam controller dongles since im uisng a WMR steam vr hybrid

**Comment by skyrockss** [comment]
okay so update I created a system report in steam vr and it says next to the base stations (update necessary) yet in steam vr there is no option to update them so should I just contact steam?  
![image](https://user-images.githubusercontent.com/75432389/101164738-5fc07580-35ea-11eb-9c9b-5df0c90a3482.png)

**Comment by nouser2013** [comment]
yes, I'd suggest to do so and open a ticket with them. Perhaps they can be of help.

Other than that, you could try to borrow a Valve Headset, because FW update for base stations might not be possible through the dongle. Perhaps it's not implemented there, only in the HMDs.

**Comment by skyrockss** [comment]
ah got it. I sent a ticket to valve so hopefully they can help me

**Comment by skyrockss** [comment]
Hello so turns out my base stations are from HTC and HTC nor Valve would help me in this case so I bought a valve index and I am not waiting for it to arrive to see if I can update the base stations and then test your program!

**Comment by skyrockss** [comment]
Got the index, Base stations finally updated, program works perfect.

**Comment by nouser2013** [comment]
ah very nice, glad to hear it :)
