### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by Fatalution** [nouser2013/lighthouse-v2-manager#7]
The exe just halts in a loop after running the shortcut. Worked fine on Windows 10.
![image](https://user-images.githubusercontent.com/17583199/139334360-40fa4bd1-6b5e-4030-bd22-df1a6ace48c1.png)

Can something be done?

**Comment by pooyashahidi** [comment]
just wanted to confirm that the python version works fine on windows 11 (build 22489) thanks :)

**Comment by MirkoHuf** [comment]
Hi, installes python 3.9.9 and bleak-0.14.1-py2.py3-none-any.whl / bleak_winrt-1.1.0-cp39-cp39-win_amd64.whl - but:

```
python.exe .\lighthouse-v2-manager.py discover

=== LightHouse V2 Manager ===

>> MODE: discover suitable V2 lighthouses

>> Discovering BLE devices...
>> Sorry, not suitable V2 Lighthouses found.
```

With the last windows version it found at least one device (but can't turn it on or off).
Any hints?
Thanks in advance.

**Comment by veryoldboy** [comment]
Arghh... indeed not working under Win11 .... hope someone fixes it

**Comment by nouser2013** [comment]
Sorry, I don't have Win11. It seems BLE stack related, so given that all the libs are the latest versions, I'm afraid we're out of luck for the moment. In case you're wondering what it does, I put all that in the PiMAX forum here: 
* [Characteristic Description](https://community.openmr.ai/t/how-to-power-off-basestations-remotely-solved/15205/203)
* [Advertisement Data Description](https://community.openmr.ai/t/how-to-power-off-basestations-remotely-solved/15205/209)

Maybe you can whip something up with a different / windows-native C++ code app?

**Comment by nouser2013** [comment]
One additional remark: mannix has created a new project for BS V1 and V2, here:
* https://github.com/mann1x/BSManager 

Maybe this works for you guys as well.

**Comment by AphLute** [comment]
Thanks for all the ideas here.  I got it working on Windows 11 using voip's instructions.

I also installed `pip3 install nest_asyncio` to fix an error about the loop.

I was still getting crashes about a `NoneType` so I created a patch that fixes it.  I don't know if that's Windows 11, or maybe there are just weird unnamed bluetooth devices around or something.  https://github.com/nouser2013/lighthouse-v2-manager/pull/11

**Comment by nouser2013** [comment]
Hi all, there have been some commits to apparently fix win11 and bleak issues. Could you verify that it now works? Then I could close the issue.

**Comment by benbiron** [comment]
Worked for me. I installed Python 3.11 from the Windows store, then:
`pip3 install bleak`
`pip3 install winshell`
`pip3 install pywin32`
`python lighthouse-v2-manager.py discover -cs`
And I now have 2 desktop shortcuts that can be used to toggle the light houses on/off.

Thanks!
